### ISSUE TITLE
Images will not be shown on collaborative browser

### ISSUE THREAD

**Issue by optiprime** [abdulaziz-git/excalidraw-docker#1]
When creating images, my collaboration partner will only see an empty image border with a generic image icon. On both sides an exception in the javascript console is shown:

FirebaseError: "projectId" not provided in firebase.initializeApp.
    at new e (prebuilt-4888bff0-430c65bc.js:180:23)
    at prebuilt-4888bff0-430c65bc.js:14732:91
    at e.t (prebuilt-4888bff0-430c65bc.js:14731:28)
    at new e (prebuilt-4888bff0-430c65bc.js:15300:23)
    at index.ts:41:9
    at e.instanceFactory (config.ts:80:16)
    at e.getOrInitializeService (provider.ts:265:33)
    at e.getImmediate (provider.ts:113:21)
    at e._getService (firebaseApp.ts:126:54)
    at e.firestore (firebaseNamespaceCore.ts:228:29)
overrideMethod @ react_devtools_backend.js:4061
(anonymous) @ CollabWrapper.tsx:236
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Portal.tsx:176
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Portal.tsx:22
(anonymous) @ Portal.tsx:39
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Portal.tsx:38
(anonymous) @ index.js:145
(anonymous) @ socket.js:278
(anonymous) @ socket.js:240
(anonymous) @ index.js:21
(anonymous) @ index.js:145
(anonymous) @ manager.js:349
(anonymous) @ index.js:21
(anonymous) @ index.js:145
(anonymous) @ index.js:251
(anonymous) @ manager.js:339
(anonymous) @ index.js:21
(anonymous) @ index.js:145
(anonymous) @ socket.js:461
(anonymous) @ socket.js:278
(anonymous) @ index.js:145
(anonymous) @ transport.js:149
(anonymous) @ transport.js:141
(anonymous) @ websocket.js:160
Show 17 more frames

As suggested in the README, my .env has an empty setting for REACT_APP_FIREBASE_CONFIG. Should I set something else to avoid this error?

**Comment by abdulaziz-git** [comment]
Hi, I'm also getting the same error in my excalidraw app but mine is working fine for collaboration functions
you can check it here : [draw.qrku.net](https://draw.qrku.net)

Maybe you should check the official repo here: https://gitlab.open-mind.space/pandel/excalidraw-docker

**Comment by mqu** [comment]
@abdulaziz-git : it does not work any more. I am have a message "loading scene", but never see diagram.

**Comment by abdulaziz-git** [comment]
@optiprime @mqu you can use this to self-hosted excalidraw

- https://gitlab.com/kiliandeca/excalidraw-fork
- https://github.com/b310-digital/excalidraw

**Comment by mqu** [comment]
> @optiprime @mqu you can use this to self-hosted excalidraw
> 
>     * https://gitlab.com/kiliandeca/excalidraw-fork
> 
>     * https://github.com/b310-digital/excalidraw

thanks : I can see this commit :  [removed firebase and added support for rooms without firebase](https://github.com/b310-digital/excalidraw/commit/91fc29bfcdbfdd38d8ffa8eaeba2389c2a156855) . Very nice, I will try this.
